openapi: 3.0.3
info:
  version: 0.0.1
  title: recipe API
paths:
  /recipes:
    get:
      operationId: GetRecipes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRecipesResponseBody"
    post:
      operationId: AddRecipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostRecipeRequestBody"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostRecipeResponseBody"
        default:
          description: Recipe POST Error response
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/PostRecipeErrorResponseBody"
  /recipes/{recipeId}:
    get:
      operationId: GetRecipeByRecipeId      
      parameters:
        - name: recipeId
          in: path
          description: ID of recipe to return
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        "200":
          description: OK          
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRecipeResponseBody"
    patch:
      operationId: UpdateRecipeByRecipeId    
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchRecipeRequestBody"  
      parameters:
        - name: recipeId
          in: path
          description: ID of recipe to update
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        "200":
          description: OK          
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatchRecipeResponseBody"
    delete:
      operationId: DeleteRecipeByRecipeId      
      parameters:
        - name: recipeId
          in: path
          description: ID of recipe to delete
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        "200":
          description: OK          
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteRecipeResponseBody"
    
          
            
      
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: uint64
        title:
          type: string
        making_time:
          type: string
        serves:
          type: string
        ingredients:
          type: string
        cost:
          type: integer
      required:
        - "id"
        - "title"
        - "making_time"
        - "serves"
        - "ingredients"
        - "cost"
    IdLessRecipe:
      type: object
      properties:
        title:
          type: string
        making_time:
          type: string
        serves:
          type: string
        ingredients:
          type: string
        cost:
          type: integer
      required:
        - "title"
        - "making_time"
        - "serves"
        - "ingredients"
        - "cost"
    PostedRecipe:
      type: object
      properties:
        id:
          type: integer
          format: uint64
        title:
          type: string
        making_time:
          type: string
        serves:
          type: string    
        ingredients:
          type: string
        cost:
          type: integer      
        created_at:
          type: string 
          format: date-time
        updated_at:
          type: string 
          format: date-time
      required:
        - "id"
        - "title"
        - "making_time"
        - "serves"
        - "ingredients"
        - "cost"
        - "created_at"
        - "updated_at"    
    PostRecipeRequestBody:
      $ref: "#/components/schemas/IdLessRecipe"
    PatchRecipeRequestBody:
      $ref: "#/components/schemas/IdLessRecipe"
    GetRecipesResponseBody:
      type: object
      properties:
        recipes:
          type: array
          items: 
            $ref: "#/components/schemas/Recipe"
    PostRecipeResponseBody:
      type: object
      properties:
        recipe:
          type: array
          items: 
            $ref: "#/components/schemas/PostedRecipe"
    PostRecipeErrorResponseBody:
      type: object
      properties:
        message:
          type: string
        required:
          type: string
    GetRecipeResponseBody:
      type: object
      properties:
        message: 
          type: string
        recipe:
          type: array
          items: 
            $ref: "#/components/schemas/Recipe"
    PatchRecipeResponseBody:
      type: object
      properties:
        message: 
          type: string
        recipe:
          type: array
          items: 
            $ref: "#/components/schemas/IdLessRecipe"
    DeleteRecipeResponseBody:
      type: object
      properties:
        message: 
          type: string
      