// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package schema

import (
	"time"
)

// DeleteRecipeResponseBody defines model for DeleteRecipeResponseBody.
type DeleteRecipeResponseBody struct {
	Message *string `json:"message,omitempty"`
}

// GetRecipeResponseBody defines model for GetRecipeResponseBody.
type GetRecipeResponseBody struct {
	Message *string   `json:"message,omitempty"`
	Recipe  *[]Recipe `json:"recipe,omitempty"`
}

// GetRecipesResponseBody defines model for GetRecipesResponseBody.
type GetRecipesResponseBody struct {
	Recipes *[]Recipe `json:"recipes,omitempty"`
}

// IdLessRecipe defines model for IdLessRecipe.
type IdLessRecipe struct {
	Cost        int    `json:"cost"`
	Ingredients string `json:"ingredients"`
	MakingTime  string `json:"making_time"`
	Serves      string `json:"serves"`
	Title       string `json:"title"`
}

// PatchRecipeRequestBody defines model for PatchRecipeRequestBody.
type PatchRecipeRequestBody = IdLessRecipe

// PatchRecipeResponseBody defines model for PatchRecipeResponseBody.
type PatchRecipeResponseBody struct {
	Message *string         `json:"message,omitempty"`
	Recipe  *[]IdLessRecipe `json:"recipe,omitempty"`
}

// PostRecipeErrorResponseBody defines model for PostRecipeErrorResponseBody.
type PostRecipeErrorResponseBody struct {
	Message  *string `json:"message,omitempty"`
	Required *string `json:"required,omitempty"`
}

// PostRecipeRequestBody defines model for PostRecipeRequestBody.
type PostRecipeRequestBody = IdLessRecipe

// PostRecipeResponseBody defines model for PostRecipeResponseBody.
type PostRecipeResponseBody struct {
	Recipe *[]PostedRecipe `json:"recipe,omitempty"`
}

// PostedRecipe defines model for PostedRecipe.
type PostedRecipe struct {
	Cost        int       `json:"cost"`
	CreatedAt   time.Time `json:"created_at"`
	Id          uint64    `json:"id"`
	Ingredients string    `json:"ingredients"`
	MakingTime  string    `json:"making_time"`
	Serves      string    `json:"serves"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Recipe defines model for Recipe.
type Recipe struct {
	Cost        int    `json:"cost"`
	Id          uint64 `json:"id"`
	Ingredients string `json:"ingredients"`
	MakingTime  string `json:"making_time"`
	Serves      string `json:"serves"`
	Title       string `json:"title"`
}
