// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package schema

import (
	"time"
)

// DeleteRecipeResponseBody defines model for DeleteRecipeResponseBody.
type DeleteRecipeResponseBody struct {
	Message *string `json:"message,omitempty"`
}

// GetRecipeResponseBody defines model for GetRecipeResponseBody.
type GetRecipeResponseBody struct {
	Message *string   `json:"message,omitempty"`
	Recipe *[]Recipe `json:"recipe,omitempty"`
}

// GetRecipesResponseBody defines model for GetRecipesResponseBody.
type GetRecipesResponseBody struct {
	Recipes *[]Recipe `json:"recipes,omitempty"`
}

// NoIndexedRecipe defines model for NoIndexedRecipe.
type NoIndexedRecipe struct {
	Cost       string `json:"cost"`
	Ingredients string `json:"Ingredients"`
	MakingTime string `json:"making_time"`
	Serves     string `json:"serves"`
	Title      string `json:"title"`
}

// PatchRecipeRequestBody defines model for PatchRecipeRequestBody.
type PatchRecipeRequestBody = NoIndexedRecipe

// PatchRecipeResponseBody defines model for PatchRecipeResponseBody.
type PatchRecipeResponseBody struct {
	Message *string            `json:"message,omitempty"`
	Recipe *[]NoIndexedRecipe `json:"recipe,omitempty"`
}

// PostRecipeErrorResponseBody defines model for PostRecipeErrorResponseBody.
type PostRecipeErrorResponseBody struct {
	Message  *string `json:"message,omitempty"`
	Required *string `json:"required,omitempty"`
}

// PostRecipeRequestBody defines model for PostRecipeRequestBody.
type PostRecipeRequestBody = NoIndexedRecipe

// PostRecipeResponseBody defines model for PostRecipeResponseBody.
type PostRecipeResponseBody struct {
	Recipe *[]PostedRecipe `json:"recipe,omitempty"`
}

// PostedRecipe defines model for PostedRecipe.
type PostedRecipe struct {
	Cost       string    `json:"cost"`
	CreatedAt  time.Time `json:"created_at"`
	Id         uint64    `json:"id"`
	Ingredients string    `json:"Ingredients"`
	MakingTime string    `json:"making_time"`
	Serves     string    `json:"serves"`
	Title      string    `json:"title"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// Recipe defines model for Recipe.
type Recipe struct {
	Cost       string `json:"cost"`
	Id         uint64 `json:"id"`
	Ingredients string `json:"Ingredients"`
	MakingTime string `json:"making_time"`
	Serves     string `json:"serves"`
	Title      string `json:"title"`
}
